### ISSUE TITLE
Cannot find module '@minify-html/node-darwin-arm64'

### ISSUE THREAD

**Issue by ExecuteMyExecution** [theme-shoka-x/hexo-lightning-minify#6]
run：`hexo new "test post"`

Error：
<img width="616" alt="image" src="https://github.com/theme-shoka-x/hexo-lightning-minify/assets/52079597/cb7bcd93-3d55-40e6-8b58-686e12aeea3b">

芯片是Apple M1

**Comment by D-Sketon** [comment]
手动安装一下这个包

**Comment by ExecuteMyExecution** [comment]
没有arm64，其他的倒是有

**Comment by D-Sketon** [comment]
https://github.com/wilsonzlin/minify-html/issues/172
minify-html本身的问题

**Comment by ExecuteMyExecution** [comment]
解决了：https://dev.to/krishna121996/how-to-fix-cannot-find-module-node-darwin-arm64packagejson-10i2
